### ISSUE TITLE
Unique name for each batch of jobs

### ISSUE THREAD

**Issue by MarcCote** [SMART-Lab/smartdispatch#11]
Right now, if we launch multiple batch of jobs (batch => call to smartDispatch.py) the same Name will be reused.

| Job id | Name | User | Time Use | S | Queue |
| --- | --- | --- | --- | --- | --- |
| 24834.mp2 | jobCommands_0.sh | stjeans1 | 50:58:21 | R | qwork4 |
| 24835.mp2 | jobCommands_1.sh | stjeans1 | 64:02:49 | R | qwork4 |
| 24836.mp2 | jobCommands_2.sh | stjeans1 | 43:58:09 | R | qwork4 |
| 24837.mp2 | jobCommands_0.sh | stjeans1 | 51:58:06 | R | qwork4 |
| 24838.mp2 | jobCommands_1.sh | stjeans1 | 23:22:10 | R | qwork4 |
| 24839.mp2 | jobCommands_2.sh | stjeans1 | 63:27:05 | R | qwork4 |

**Comment by mgermain** [comment]
Putting the commandUID won't work because there can by as many command in a job as the user want. So in the end I think it should be {batchUID}_# instead of jobCommands_#.sh

We should probably use the PBS option jobNAME and juste name the files job_1.sh ... or name them the same ?

**Comment by MarcCote** [comment]
I would prefer naming them the same using {batchUID}# as you proposed.

**Comment by mgermain** [comment]
You mean having the file AND the jobname set to {natchUID} ?

**Comment by MarcCote** [comment]
Thinking over, let's go with what you proposed. That is, using PBS option -jobname (needs to check what is the actual name here) to set {batchUID}# as the name of the PBS job. Regarding the files contained in `{batchUID}/commands/` we can let them to `job_#.sh`.

**Comment by negar-rostamzadeh** [comment]
Since batchUID contains the name of the user and the name of the script, with the suggested naming system, we will end up with having long names. Then what will happen is that: when we call qstat, we are usually just seeing the end of the file name. Then we will running to the same issue when we are checking the jobs using qstat (when we have multiple batches of jobs):

138498.gpu-srv1            ...menegartestsh_0 negar           00:00:00 C test           
138499.gpu-srv1            ...menegartestsh_1 negar           00:00:00 C test           
138500.gpu-srv1            ...menegartestsh_0 negar           00:00:00 C test  
-----------------------------
So do you propose a better job naming system that be both representative of the job and also short enough to prevent confusion in qstat output?
