### ISSUE TITLE
Getting more than one GPU is not intuitive

### ISSUE THREAD

**Issue by rizar** [SMART-Lab/smartdispatch#124]
I had to pass both `-g 2` and `-G 2`.

**Comment by mgermain** [comment]
Usually, you only need -g2 that says that each of your commands will need 2 GPUs.

If you need to specify -G2 it's probably because you are trying to run on a queue that has only one GPU like gpu_1 and that you need to override the defaults of the queue.

The error thrown is probably not clear and it could be handled more gracefully.

**Comment by mgermain** [comment]
Created issue #155 to solve this.
