### ISSUE TITLE
Bug with --coresPerNode and  --gpusPerNode

### ISSUE THREAD

**Issue by mgermain** [SMART-Lab/smartdispatch#99]
When launching:
smart_dispatch.py -q gpu_1 --coresPerNode=2 --gpusPerNode=1 -x -t 10:00 launch nvidia-sm

The PBS generated will be wrong.
It does `#PBS -l nodes=1:gpus=2` instead of `#PBS -l nodes=2:gpus=1`

**Comment by bouthilx** [comment]
Thanks to @Dutil's investigation, the problem comes from the fact that Helios job generator removes ppn because this option is invalid for this cluster. K20's job get 5 cores assigned and K80's get 3 cores, both getting 2 gpus.
So the value of PBS should indeed be -l nodes=1:gpus=2. The problem is this modifications is done without any warnings to the user who tries to specify something else.

Looking at the other job generators, it appears Helios is not the only one to behave differently than what the user would expect.

## Helios [doc](https://wiki.calculquebec.ca/w/Ex%C3%A9cuter_une_t%C3%A2che/en#tab=tab6)
Removes ppn=*, set gpus=2

But cluster behavior is: 
- If you get K80, you have 3 cores and 2 gpus
- If you get K20, you have 5 cores and 2 gpus

Because of this, division of commands for workers is incorrect if it tries to assign commands using more than the availlable cores (3 or 5).

## Hades [doc](https://wiki.calculquebec.ca/w/Ex%C3%A9cuter_une_t%C3%A2che/en#tab=tab5)
Removes ppn=*, set ppn=`nb of gpus`

But cluster behavior is: 
- No constraints on ppn.
- To get all 8 cores, set ppn=7.

This unables user from using many cpus with less gpus. I don't see why it should do so given Hades' doc.

## Mammouth [doc](https://wiki.calculquebec.ca/w/Ex%C3%A9cuter_une_t%C3%A2che/en#tab=tab7)
Removes ppn=*, set ppn=1

Cluster behavior is: 
Scheduler only see one core per node (even though there is 12), so node=1:ppn=1 gives 12 cores.

Because of this, division of commands for workers simply cannot fit more than one core per job, while the nodes actually have 12 cores each.

---

@mgermain @MarcCote I'd like to know why those substitutions were implemented that way. Was the worker system added later on?

**Comment by nouiz** [comment]
I think the cluster config was done with some idea in mind, but make it hard to use in other case like our.

So it seam we can't rely on all cluster to handle the jobs as we want. The way jobdispatch supported that was by handling itself part of the submission by bunding jobs together to do what we want whatever the cluster allow.

If you need more information about how it was solved, tell me.

**Comment by bouthilx** [comment]
@nouiz Thank you now the worker system makes much more sense to me! I didn't realize it could be a way to get around the weird clusters' scheduler behaviors. I just noticed that the dispatching of the commands is done before ppn= and gpus= are modified. So it is not true that the dispatching is incorrect. I'll look at the code again and see what it implies. Anyhow, I won't close this issue until we have a clear warning to users to avoid further confusion.

**Comment by nouiz** [comment]
We don't need just a clear warning. We need a way for the user to don't
know about this.
A local config on each cluster could tell smart-dispatch how to bundle. We
need to bundle the less frequently possible. Always bunding per node would
not be great. It would cause a lower utilisation of the cluster.

**Comment by bouthilx** [comment]
> We don't need just a clear warning. We need a way for the user to don't know about this.

Yes and no. 

Yes) The user should not be warned about this when launching command line.
No) Looking at the PBS file generated could be quite confusing. Adding a "warning" comment in the PBS file around ppn and gpus settings would help clarify. 

> We need to bundle the less frequently possible. Always bunding per node would
not be great. It would cause a lower utilisation of the cluster.

I totally agree. The smaller the better for the scheduler.

**Comment by nouiz** [comment]
Agree for a watching in the PBS file. I was thinking you wanted a watching
printed on the command line.

**Comment by mgermain** [comment]
@bouthilx no. "So the value of PBS should indeed be -l nodes=1:gpus=2." 

gpus should not be equal to 2 as it is on the queue gpu_1 which contains only 1 GPU per node. Asking for 2 GPU in 1  node on a queue that only contains 1 results in an invalid batch file. That's the only problem related to this issue. Nothing else :p

**Comment by bouthilx** [comment]
@mgermain Yeah I forgot to revisit my message after we had a chat about the issue. So is this bug supposed to occur on every cluster or on a single one? Do you remember?

**Comment by mgermain** [comment]
As far as I remember it was only on Helios but we would have to test on the
others anyway.

**Comment by mgermain** [comment]
I've just retested it and as @Dutil  says it's been fixed in the past. I've tested it on Helios and Guillimin (the 2 with gpus) and it's functional now.
Closing the issue.

**Comment by bouthilx** [comment]
Wow 2/2 tickets for @Dutil were already fixed.
